apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - namespace.kafka:9092  # note the kafka namespace
  topics:
  - poc-knative-lambda-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: poc-knative-lambda